### ISSUE TITLE
Docker Creation failed (armhf)  

### ISSUE THREAD

**Issue by boldiebold** [d8ahazard/HueDream#14]
**Docker build failed using dockerfile.armhf.** 
using QNAP TS431-P2, Alpine AL314 Quad-core ARM Cortex-A15 CPU @ 1.70GHz

Try different .Net Core Builds (alpine, buster etc..) with no success,
Any help would be great.  

Thanks a lot for your great work and support.
Please find the log above

[/var/lib/docker/glimmr-master] # docker build .
Sending build context to Docker daemon  104.7MB
Step 1/29 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim-arm32v7 AS base
 ---> 18d77ca59068
Step 2/29 : ENV ASPNETCORE_URLS http://+:5699
 ---> Using cache
 ---> 5d3a27cd0d67
Step 3/29 : WORKDIR /app
 ---> Using cache
 ---> 621dbc8bf2a3
Step 4/29 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7 AS build
 ---> 688d510e8d3a
Step 5/29 : WORKDIR /src
 ---> Using cache
 ---> 88d33c209d9d
Step 6/29 : COPY HueDream.csproj 
 ---> Using cache
 ---> 51bd1ce544a4
Step 7/29 : COPY pkg /root/pkg
 ---> Using cache
 ---> d3425341c30b
Step 8/29 : COPY build/arm /root/
 ---> Using cache
 ---> 8b22200b735d
Step 9/29 : COPY NuGet.Config ~/.nuget/packages
 ---> Using cache
 ---> 1678e8a80584
Step 10/29 : RUN dotnet restore --source "/root/pkg" --source "https://api.nuget.org/v3/index.json" --source "https://www.myget.org/F/mmalsharp/api/v3/index.json"
 ---> Using cache
 ---> e05c44c29c5d
Step 11/29 : RUN dotnet restore "./HueDream.csproj"
 ---> Using cache
 ---> 99166d52bae4
Step 12/29 : COPY . .
 ---> Using cache
 ---> b82b612ea25e
Step 13/29 : WORKDIR "/src/."
 ---> Using cache
 ---> b9cb8371b3c6
Step 14/29 : RUN dotnet build "HueDream.csproj" -c Release -o /app/build
 ---> Running in 1e9e04dc77bb
Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/src/HueDream.csproj : warning NU1701: Package 'Pranas.ScreenshotCapture 1.0.11' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
/src/HueDream.csproj : warning NU1701: Package 'ZedGraph.WinForms 6.0.0-alpha0001' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
  Restored /src/HueDream.csproj (in 3.26 sec).
  Emgu CV nuget package compiling against WindowsForms
  Emgu CV compiling with x86 x64 binary
  Emgu CV nuget package compiling against Raspbian_arm
  Emgu CV compiling with arm binary
/src/HueDream.csproj : warning NU1701: Package 'Pranas.ScreenshotCapture 1.0.11' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
/src/HueDream.csproj : warning NU1701: Package 'ZedGraph.WinForms 6.0.0-alpha0001' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
/usr/share/dotnet/sdk/3.1.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(283,5): error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App.WindowsForms' was not recognized [/src/HueDream.csproj]

Build FAILED.

/src/HueDream.csproj : warning NU1701: Package 'Pranas.ScreenshotCapture 1.0.11' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
/src/HueDream.csproj : warning NU1701: Package 'ZedGraph.WinForms 6.0.0-alpha0001' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
/src/HueDream.csproj : warning NU1701: Package 'Pranas.ScreenshotCapture 1.0.11' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
/src/HueDream.csproj : warning NU1701: Package 'ZedGraph.WinForms 6.0.0-alpha0001' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
/usr/share/dotnet/sdk/3.1.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(283,5): error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App.WindowsForms' was not recognized [/src/HueDream.csproj]
    4 Warning(s)
    1 Error(s)

Time Elapsed 00:00:08.60
The command '/bin/sh -c dotnet build "HueDream.csproj" -c Release -o /app/build' returned a non-zero code: 1

**Comment by d8ahazard** [comment]
Hey there!

New issue I've created by updating Emgu.CV to version 4.3, which apparently accidentally introduced a dependency on the windowsForms framework, even though it's a .net core library.

There is already an issue open for Emgu.CV regarding this, and they are working on creating the new 4.4 library which removes this unnecessary dependency. I will be updating my code when the new library is available.

https://github.com/emgucv/emgucv/issues/339

**Comment by d8ahazard** [comment]
Just an update:

I've got the 4.4 nuget packages for windows, but need to manually compile
the lib for linux-arm. I've had trouble in the past doing this with a pi3,
but I've since bought a pi 4, so hopefully it will compile with a faster
machine. If that works, then I can get it fixed today yet.

**Comment by boldiebold** [comment]
Please allow me to ask how it went?
Were you able to get it compiled ?
