### ISSUE TITLE
How to properly create the docker on Pi???

### ISSUE THREAD

**Issue by Squra309** [d8ahazard/HueDream#18]
Hi there,

I just ran into this project, but i run into issues. I was able to login with SSH and managed to install the git repo properly. But, I can’t seem to manage to login on the webui. 

What does it need to get properly setup on the rpi?

I got the glimmr directory and setup_pi.sh already installed! But that command of the docker looks like a Windows command or something because it gives the cli response no such command. 

Can anybody please give the right code including parameters for the raspberry pi?

Thanks in advance!

Be safe all!

**Comment by d8ahazard** [comment]
If you're running it on a Pi, you don't necessarily need docker?

I am presently smack-dab in the middle of a massive refresh specifically
targeted at the Pi. In the /dev branch, I've updated the setup_pi.sh script
quite a bit, as well as rolled up to .Net 5, switched to a liteDB for data
storage, and completely overhauled the background services that make
everything go.

However, this isn't quite ready for consumption yet, so if you wait a few
days, I'll probably have merged it to the Master branch, at which time, you
can try again.

You can also refer to the "setup_pi.sh" script in the /dev branch to see
what things I've fixed and changed.

For docker - I've not gotten there yet with the new version. That will
follow getting all the stuff above I mentioned straightened out.

I'll *also* be releasing flashable raspi images based on raspbian lite and
desktop versions that should be just plug and play. Flash it, edit the
wpa_supplicant file to configure wifi, and turn it on.

So, sorry you're presently having issues, but in a few days, everything
should "just work" again.

>
