### ISSUE TITLE
Raspberry PI Support

### ISSUE THREAD

**Issue by cfoucher** [d8ahazard/HueDream#2]
Thanks for creating this! super excited to try it out. 

I'm hoping to get it running on my raspberry pi 3. Any plans to publish a armhf compatible docker build?

I've also tried to install it manually but get the following error when running it:

```
mono --debug HueDream
Cannot open assembly 'HueDream': File does not contain a valid CIL image.
```

Thanks!

**Comment by d8ahazard** [comment]
Totally! That's where I pictured it running. I have to research the
specifics, but the docker file is the default created with vscode. I think
it's just finding the appropriate Ms docker image and copying.

I'll research this later tonight.

**Comment by d8ahazard** [comment]
@cfoucher - Created an armf dockerfile, but don't have my pi set up right now. Would you care to test and report back?

**Comment by cfoucher** [comment]
Awesome!
Looks like it builds and runs. I'm not at home at the moment so I will have to test it fully tonight. 

One other question, I'm hoping to run it behind a domain so I have a proxy set up `mydomain.com/huedream`. Is it possible to set a URL base (i.e. `/huedream`) in order to support the reverse proxy?

**Comment by cfoucher** [comment]
It looks to be working fine, but I didn't realize my Gledopto bulbs couldn't be grouped into entertainment areas. I will have to look into getting a couple of real hue bulbs. Thanks for your work on this though! It's really impressive!

**Comment by d8ahazard** [comment]
Cool. I'm going to close this for now until it can be tested further, or until I get docker running on my pi, or set up an emulator...
