### ISSUE TITLE
About the HDMI capture board

### ISSUE THREAD

**Issue by xfce** [d8ahazard/HueDream#45]
Hi 
        I Can't find the info about the HDMI capture board, does this is a closed hardware board? If I  only have a raspberry Pi or install the software on PC how can I play? Thanks

**Comment by RobertD502** [comment]
The HDMI capture is done with a simple USB HDMI capture card such as [this](https://www.amazon.com/gp/product/B08HGZF6X9). If you are planning on installing Glimmr on your PC then you can bypass the HDMI splitter and HDMI USB capture altogether as Glimmr can grab the screen that is directly connected to the PC running Glimmr.

If you want to use Glimmr to capture video from another device (Apple TV, Nvidia Shield, etc), then you'll need to use a HDMI splitter as well as a USB HDMI capture device.
