### ISSUE TITLE
Github release download link fix for Linux script needed

### ISSUE THREAD

**Issue by RobertD502** [d8ahazard/HueDream#48]
Hey Ben, hope all is well!

I noticed that the update through the Glimmr UI didn't take. I then tried to manually rerun the `linux_setup.sh` script and noticed it failed as well.

The root of the problem is how the releases are named vs what the script is looking for.
For example, for `1.3.0`, the script is looking for `https://github.com/d8ahazard/glimmr/releases/download/$ver/Glimmr.$ver.$PUBFILE.tar.gz` which leads to a link of `https://github.com/d8ahazard/glimmr/releases/download/1.3.0/Glimmr.1.3.0.linux-arm64.tar.gz`. However, the actual file name / link is `https://github.com/d8ahazard/glimmr/releases/download/1.3.0/Glimmr.1.3.0-master-0001164.linux-arm64.tar.gz`.

I'm assuming you are building this locally since I don't see any actions that can be edited to disabled adding the `-master-0001164` portion when creating the archive. This may be affecting other installs as well - I haven't checked as I just got around to noticing the fault in the Linux installation.

**Comment by d8ahazard** [comment]
Yep. And good thing too. Need to do some updates yet, should probably be pushing a new release/image tonight after work.

New RPI image + new build = 60+FPS consistently:

<img width="1200" alt="image" src="https://github.com/d8ahazard/glimmr/assets/1633844/e94de621-cd8c-4e06-a9a4-b0f7b8b78a72">
