### ISSUE TITLE
Blank Target Dreamscreen Dropdown

### ISSUE THREAD

**Issue by bs3-tech** [d8ahazard/HueDream#8]
Windows 10

On the browser setup page, there are no values to choose from for Target Dreamsceen. 
In the Hue section, none of the settings are functional and do not respond to clicking.
I have tried all 3 browsers and none showed values to choose from.

I can tell HueDream has connected to the Hue bridge because it has correctly identified its IP address in the command window

Another piece of possibly helpful background: I am able to connect to the simulated sidekick in the dreamscreen app, though of course no lights have been assigned.  So all 3 gadgets - HueDream app, Hue bridge and Dreamscreen appear to have connectivity, just no dropdowns to set up the lights.

Also, as another reported, HueDream is listening on 5000 rather than 5666.  This part is not necessarily a problem for me once I figured it out...just feedback

Thank you for any advice in getting up and running.

**Comment by schhim** [comment]
I'm having the same issues you're describing. I managed to get the Dreamscreen to show up once but the lights never sync'd with the DS.

**Comment by d8ahazard** [comment]
Hey guys, sorry about the issues.

If running under windows, you'll need to make sure the app is allowed
through windows firewall, as it needs to talk over UDP to find DS devices
and Bridges.

I'm working on an update that will drastically overhaul how everything is
set up - stay tuned for the next release, and hopefully any other issues
not related to firewalls will be resolved.

**Comment by schhim** [comment]
Thanks for the update! Somehow, the DS magically appeared in the dropdown but the hue lights aren't responding to any controls. It shows huedream is linked to my hue bridge and I see my entertainment area but I must be missing something. TIA!

**Comment by d8ahazard** [comment]
With the entertainment area showing, have you selected which regions of the
screen to map to which lights?

If so, please provide console output after you stop/start streaming from
the DS app.

**Comment by schhim** [comment]
When I open up the browswer console, I'm getting a websocket connection failure, unexepected response code: 404.

**Comment by d8ahazard** [comment]
That's actually just an un-implemented feature.

Are you running in docker, or natively?

**Comment by schhim** [comment]
I'm running it natively. Windows 10 on Chrome.
![huedream console](https://user-images.githubusercontent.com/60415709/73599882-9e8b2800-450e-11ea-9a8c-30c64daf98c5.PNG)
